### ISSUE TITLE
expected package, found import

### ISSUE THREAD

**Issue by Francisobiagwu** [lukechampine/lthash#1]
can't load package: package .: 
test.go:2:1: expected 'package', found 'import'

I tried running the go lthash program, so I created a test file (test.go), then copied and pasted the code provided on readme. But I was getting the above error

**Comment by lukechampine** [comment]
I omitted the `package main` declaration for brevity. The code won't compile anyway, since the `oldSum` and `newSum` variables are unused. I'll strip out some more surrounding boilerplate to make it more obvious that this isn't standalone code.

**Comment by Francisobiagwu** [comment]
Please, can you make this code available in Python too? I'm not too
familiar with go as I am with python.

**Comment by lukechampine** [comment]
I am the opposite, so sadly I cannot help you. However, the code is conceptually very simple, and should be easy to port if you have a Python implementation of BLAKE2x. I googled around and couldn't find any, but then again, I don't really know where to look.

**Comment by Francisobiagwu** [comment]
Thanks.
Using the program you provided, what is the syntax to verify if 'Banana' or
anything is contained in the hash?


Kind regards,
*Francis Obiagwu.*

**Comment by lukechampine** [comment]
LtHash does not support checking for the presence of an arbitrary element. You can only check whether the hash covers a given set.

For example, say you calculate the hash of the elements `"Apple" + "Banana" + "Grape"`. You cannot check whether this hash contains `"Apple"`. You can only check whether the hash is  `"Apple" + "Banana" + "Grape"` or something else.

If you want to check for the presence of an arbitrary element, a Merkle tree is probably your best bet. There is active research into [accumulators](https://en.wikipedia.org/wiki/Accumulator_(cryptography)) (such as RSA accumulators) that may also be of interest.

**Comment by Francisobiagwu** [comment]
I've done something similar, using shingles. Where I calculated the
resemblance and containment. But those are based on sets, and they are
highly Computational expensive. More so, the size increases linearly,
unlike hash functions that are of fixed size. But sure, I will read the
recommended research.

Thanks
