### ISSUE TITLE
Idea: A cryptographic hash function using HAIFA

### ISSUE THREAD

**Issue by DonaldTsang** [lukechampine/lthash#3]
It would be useful to modift LtHash to use the HAIFA construction for a SHA3-doable hash function.
Adding a counter to each message block would make the compression function work.
See: https://eprint.iacr.org/2007/278.pdf

**Comment by lukechampine** [comment]
I'm not opposed to building on LtHash, but then it would be inaccurate to call the repo `lthash`. A new repo would be more appropriate.

**Comment by DonaldTsang** [comment]
@lukechampine something like an experiment module along side the original LtHash might be usef ul
