### ISSUE TITLE
Does this actuially uses lattices?

### ISSUE THREAD

**Issue by DonaldTsang** [lukechampine/lthash#4]
Because in https://github.com/lukechampine/lthash/blob/master/lthash.go there is no references of lattices at all while the paper cited do use lattices

**Comment by lukechampine** [comment]
I can't claim to understand the math behind this, but my understanding is that the lattice comes from treating the hash of each object as a large (1024-dimensional) vector. Adding or subtracting two such vectors preserves the security of the hash (insofar as you can't easily compute the preimage or a collision), making the construction homomorphic.

**Comment by DonaldTsang** [comment]
So it is different to NTRU or something like it?

**Comment by lukechampine** [comment]
They are similar in that they both rely on the hardness of the [shortest vector problem](https://en.wikipedia.org/wiki/Lattice_problem#Shortest_vector_problem_(SVP)) for their security. Beyond that, I can't really say.
