### ISSUE TITLE
Absolute nonsense

### ISSUE THREAD

**Issue by Eratosthenes** [lukechampine/lthash#5]
You're just adding and subtracting a hash function two bytes at a time. This doesn't satisfy a homomorphism. 

Is this really what they're doing over at Facebook? This is nonsense.

If you've created a homomorphic hash function then this test should pass:

```
func TestHomomorphism(t *testing.T) {
	var x, y [2048]byte
	copy(x[:], []byte("Hello"))
	copy(y[:], []byte("World"))
	add16(&x, &y)

	h := New16()
	h.Add(x[:])
	s1 := h.Sum(nil) // H(x + y)

	h2 := New16()
	h2.Add([]byte("Hello"))
	h2.Add([]byte("World"))
	s2 := h2.Sum(nil) // H(x) + H(y)

	// this passes if H(x + y) = H(x) + H(y), otherwise there is no homomorphism
	if !bytes.Equal(s1, s2) {
		t.Error("s1 should equal s2")
	}
}
```

**Comment by lukechampine** [comment]
Your example directly sums the bytes of the two inputs. This is not the kind of operation that LtHash is concerned with. LtHash is about set membership, not arithmetic; the homomorphism is between "adding/subtracting elements from a set" and "adding/subtracting from a hash." Hope this helps.

**Comment by Eratosthenes** [comment]
Two questions.

1) Do you know the definition of a homomorphism?

2) Which operation do you think your hash function satisfies a homomorphism under?

**Comment by lukechampine** [comment]
Take it up with the original authors, please. I implemented their algorithm because it's neat. Aside from that, I have no involvement with their work, and I'm not interested in defending it on their behalf.
